#!/usr/bin/env bash
# modules/print/printer-network-policy.sh — makes the Sentinel host the ONLY
# thing on the network that can talk to a printer (§2.2, Phase 8P).
#
# Printers are the softest device class in a tax office: unauthenticated raw
# 9100, default admin credentials, spooled client documents on internal
# storage, and scan-to-anywhere. The control is not "harden the printers", it
# is "nothing but the gateway may reach them".
#
# Three layers, generated here:
#
#   1. HOST FIREWALL (nftables) — the Sentinel host drops forwarded traffic to
#      printer ports from anything except itself. This bites when the host
#      routes the printer subnet (the NetBird-routed-printer-subnet layout for
#      firms that cannot VLAN). It is a no-op-but-harmless table otherwise.
#   2. NETBIRD POLICY — a posture rule so only the Sentinel peer's group may
#      reach the `printers` network resource. Written as JSON here and pushed
#      if a management token is available; otherwise printed for the operator.
#   3. WORKSTATION EGRESS — every Lite-managed workstation blocks outbound
#      9100/631/515 except to the gateway. That layer is generated by
#      lite/generate-lite.sh into the endpoint bundle (see
#      lite/print-queue/firewall) and is NOT this script's job; it is named
#      here so the whole model is legible in one place.
#
# Any direct print attempt to a printer IP from a workstation is what
# SENT-PR-002 fires on, sourced from CrowdSec and host-firewall logs — so the
# rules log before they drop.
#
# Usage:
#   printer-network-policy.sh [--apply|--dry-run] [--subnets 10.20.0.0/24,...]
set -euo pipefail

SENTINEL_ETC="${SENTINEL_ETC:-/etc/vibe-sentinel}"
INSTALLER_ROOT="${INSTALLER_ROOT:-/opt/vibe-sentinel-installer}"
[ -f "$INSTALLER_ROOT/lib/common.sh" ] || INSTALLER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)/vibe-sentinel-installer"
# shellcheck source=../../lib/common.sh
. "$INSTALLER_ROOT/lib/common.sh"

MODE=apply
SUBNETS_ARG=""
while [ $# -gt 0 ]; do
  case "$1" in
    --apply)    MODE=apply; shift ;;
    --dry-run)  MODE=dry-run; shift ;;
    --subnets)  SUBNETS_ARG="${2:?--subnets needs a value}"; shift 2 ;;
    --help|-h)  sed -n '2,32p' "$0"; exit 0 ;;
    *) die "Unknown argument: $1" "Run with --help for usage." ;;
  esac
done
[ "$MODE" = "dry-run" ] || require_root
require_cmd jq

STATE_DIR="$SENTINEL_ETC/modules/print"
NFT_FILE=/etc/nftables.d/vibe-print.nft
NB_POLICY="$STATE_DIR/netbird-printer-policy.json"
APPLIED_MARKER="$STATE_DIR/.printer-policy-applied"

# Printer ports: raw JetDirect, IPP, LPD, SNMP (discovery + default-cred
# checks), and the vendor admin web UIs. Admin pages must be reachable from the
# Sentinel host and from nowhere else — the Phase 8P acceptance test proves a
# non-Sentinel host cannot load them.
PRINTER_TCP_PORTS="9100,631,515,80,443,8080,9101,9102"
PRINTER_UDP_PORTS="161,162,631"

# --- Where are the printers? ------------------------------------------------
SUBNETS="$SUBNETS_ARG"
if [ -z "$SUBNETS" ]; then
  SUBNETS="$(config_get '.modules.print.printer_subnets_csv')"
fi
if [ -z "$SUBNETS" ] && [ -f "$SENTINEL_ENV_FILE" ]; then
  SUBNETS="$(grep -m1 '^PRINTER_SUBNETS=' "$SENTINEL_ENV_FILE" 2>/dev/null | cut -d= -f2- || true)"
fi
[ -n "$SUBNETS" ] || die "No printer subnet is configured, so there is nothing to isolate." \
  "Set the printer VLAN or NetBird-routed printer CIDRs and re-run, e.g.:
     printer-network-policy.sh --subnets 10.20.0.0/24
   or add PRINTER_SUBNETS=10.20.0.0/24 to $SENTINEL_ENV_FILE, or
   .modules.print.printer_subnets_csv to $SENTINEL_CONFIG.
   Until printers are on their own subnet, print isolation cannot be enforced
   at the network layer and SENT-PR-002 will not fire."

NFT_SET="$(printf '%s' "$SUBNETS" | tr ',' ' ' | tr -s ' ' | sed 's/ /, /g')"

# The Sentinel host's own addresses — the gateway is the sole permitted client.
# `|| true` matters: common.sh sets pipefail, so a host without iproute2 would
# otherwise abort here with no message at all, which is the worst way for a
# security control to fail.
HOST_ADDRS="$(ip -4 -o addr show scope global 2>/dev/null | awk '{sub(/\/.*/,"",$4); print $4}' | paste -sd', ' - || true)"
if [ -z "$HOST_ADDRS" ]; then
  log_warn "Could not enumerate this host's addresses (is iproute2 installed?). Falling back to 127.0.0.1, which will NOT match forwarded traffic."
  log      "Check the generated $NFT_FILE before relying on it."
  HOST_ADDRS="127.0.0.1"
fi

# ---------------------------------------------------------------------------
# 1. Host firewall (nftables)
# ---------------------------------------------------------------------------
NFT_RULES="$(cat <<EOF
# /etc/nftables.d/vibe-print.nft
# Generated by vibe-sentinel-installer modules/print/printer-network-policy.sh
# $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Only the Vibe Print gateway (this host) may reach printer ports. Everything
# else is logged and dropped; the log line is what SENT-PR-002 keys on.
#
# Priority -10 puts this ahead of the Docker filter-FORWARD chain so a
# container or a routed workstation cannot slip past it.

table inet vibe_print {
  set printers {
    type ipv4_addr
    flags interval
    elements = { $NFT_SET }
  }

  set gateway {
    type ipv4_addr
    flags interval
    elements = { $HOST_ADDRS }
  }

  chain forward {
    type filter hook forward priority -10; policy accept;

    # The gateway itself is always allowed through.
    ip saddr @gateway ip daddr @printers accept

    # Anything else aimed at a printer port: log, then drop.
    ip daddr @printers tcp dport { $PRINTER_TCP_PORTS } \\
      log prefix "vibe-print-deny " level warn counter drop
    ip daddr @printers udp dport { $PRINTER_UDP_PORTS } \\
      log prefix "vibe-print-deny " level warn counter drop

    # Printers must not initiate anything outward either — a printer beaconing
    # to the internet is either compromised or exfiltrating scans.
    ip saddr @printers ip daddr != @gateway \\
      log prefix "vibe-print-egress " level warn counter drop
  }
}
EOF
)"

# ---------------------------------------------------------------------------
# 2. NetBird policy — only the Sentinel peer group reaches the printer network
# ---------------------------------------------------------------------------
NB_JSON="$(jq -n --arg subnets "$SUBNETS" --arg ports "$PRINTER_TCP_PORTS" '{
  name: "vibe-sentinel: printers reachable from the print gateway only",
  description: "Phase 8P print isolation. Only the sentinel-host group may reach the printer network resource; workstations reach printers through the Vibe Print gateway on the mesh, never directly.",
  enabled: true,
  network_resource: {
    name: "printers",
    addresses: ($subnets | split(",") | map(gsub("^\\s+|\\s+$";"")))
  },
  rules: [
    {
      name: "sentinel-host -> printers",
      enabled: true,
      bidirectional: false,
      protocol: "tcp",
      ports: ($ports | split(",")),
      sources: ["sentinel-host"],
      destinations: ["printers"],
      action: "accept"
    },
    {
      name: "everything else -> printers (deny)",
      enabled: true,
      bidirectional: false,
      protocol: "all",
      sources: ["workstations", "mobile", "all"],
      destinations: ["printers"],
      action: "drop"
    }
  ]
}')"

# ---------------------------------------------------------------------------
# Emit / apply
# ---------------------------------------------------------------------------
if [ "$MODE" = "dry-run" ]; then
  echo "--- would write $NFT_FILE ---"
  printf '%s\n' "$NFT_RULES"
  echo "--- would write $NB_POLICY ---"
  printf '%s\n' "$NB_JSON"
  exit 0
fi

command -v nft >/dev/null 2>&1 || die "nftables (nft) is not installed." \
  "Install it with: apt-get install -y nftables — the host firewall is layer 1 of print isolation."

mkdir -p /etc/nftables.d "$STATE_DIR"
printf '%s\n' "$NFT_RULES" >"$NFT_FILE"
chmod 644 "$NFT_FILE"

# Replace the table atomically so a re-run never doubles the rules.
nft delete table inet vibe_print 2>/dev/null || true
if ! nft -f "$NFT_FILE"; then
  rm -f "$NFT_FILE"
  die "nftables rejected the generated printer-isolation rules." \
      "Run 'nft -c -f $NFT_FILE' to see the parse error. Check that PRINTER_SUBNETS holds valid CIDRs. No rules were left loaded."
fi
log_ok "Host firewall: only $HOST_ADDRS may reach $SUBNETS on printer ports (denies are logged as 'vibe-print-deny')"

# Persist across reboot: most distros source /etc/nftables.d from
# /etc/nftables.conf; add the include if it is missing.
if [ -f /etc/nftables.conf ] && ! grep -q 'nftables.d' /etc/nftables.conf; then
  printf '\ninclude "/etc/nftables.d/*.nft"\n' >>/etc/nftables.conf
  log_ok "Added /etc/nftables.d include to /etc/nftables.conf so the rules survive reboot"
fi
systemctl enable --now nftables >/dev/null 2>&1 || \
  log_warn "Could not enable the nftables service — the rules are loaded now but will not survive a reboot. Enable it manually: systemctl enable --now nftables"

( umask 077; printf '%s\n' "$NB_JSON" >"$NB_POLICY" )
log_ok "NetBird printer policy written to $NB_POLICY"
log    "Apply it in the NetBird admin UI (nb-admin.$(config_get '.firm.domain')) under Access Control, or POST it to the management API."
log    "The 'sentinel-host' group must contain ONLY this host's peer."

date -u +%Y-%m-%dT%H:%M:%SZ >"$APPLIED_MARKER"
chmod 644 "$APPLIED_MARKER"

hr 2>/dev/null || true
log_ok "Printer network policy applied."
log    "Layer 3 (workstation egress blocking 9100/631/515 except to the gateway) ships in the Lite bundle — see lite/print-queue/firewall."
log    "Verify: from a non-Sentinel host, a printer's admin page must NOT load. That is the Phase 8P acceptance test."
